melding = input("Skriv inn en melding Erik skal si ")
print(' ____________________')
print('< ' + melding + ' >')
print(' --------------------')
print("          \\",)
print("           \\    _______",)
print("               /       \\",)
print("              |  -   -  |",)
print("              |    ^    |",)
print("              |  \\___/  |",)
print("               \\_______/",)
print("                ___|___",)
print("               /   |   \\",)
print("              /    |    \\",)
print("                   |",)
print("                  / \\",)
print("                 /   \\",)